#!/usr/bin/env python
from __future__ import print_function
import sys, os, argparse
from io import DEFAULT_BUFFER_SIZE as DEFAULT

sys.tracebacklimit = 0
APP = "Python"
CODE = 0

def example(FILENAME):
	print(FILENAME)

def example_with_option(FILENAME):
	print("example:", FILENAME)

if __name__ == '__main__':
	try:
		parser = argparse.ArgumentParser(
				description='Example description.')
		group_one = parser.add_mutually_exclusive_group()
		group_one.add_argument('-e', '--example', help='Example option', action="store_true", default=False)
		parser.add_argument('FILE', action='store', nargs='*')
		args = parser.parse_args()

		STDIN = False
		if len(args.FILE) == 0:
			args.FILE = ['/dev/stdin']
			STDIN = True

		for ARG in args.FILE:
			if STDIN == True:
				ARGNAME = "-"
			else:
				ARGNAME = ARG
			if os.path.isdir(ARG):
				print(APP + ":", ARGNAME + ": Is a directory", file=sys.stderr)
				CODE = 1
			elif os.path.exists(ARG):
				try:
					with open(ARG) as F:
						FILEPATH = ARG
				except IOError:
					print(APP + ":", ARGNAME + ": Permission denied", file=sys.stderr)
					CODE = 1
					continue
				if args.example == False:
					example(FILEPATH)
				else:
					example_with_option(FILEPATH)
			else:
				print (APP + ":", ARGNAME + ": No such file or directory", file=sys.stderr)
				CODE = 1
	
	except KeyboardInterrupt:
		print ('')
		sys.exit(130)

sys.exit(CODE)
